name: Static Site CI/CD

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        
        steps:
        - uses: actions/checkout@v3
            
        - name: Setup Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3 
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - name: Install dependancies
          run: npm ci

        - name: Run unit tests
          run: npm run test

        - name: Run integration tests
          run: npm run test:integration

        - name: Upload coverage reports
          uses: codecov/codecov-action@v3

        - name: Validate HTML
          uses: Cyb3r-Jak3/html5validator-action@v7.2.0
          with:
            root: src/

        - name: Build artifacts
          run: |
            mkdir -p dist
            cp -r src/* dist/

        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with: 
            name: static-site-${{ matrix.node-version }}
            path: dist/

    deploy-staging:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/develop'

        steps:
        - name: Download artifacts
          uses: actions/download-artifact@v3

        - name: Deploy to IIS staging
          run: echo "Deploy to staging server"
          # TODO

    deploy-production:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
        - name: Download artifacts
          uses: actions/download-artifact@v3

        - name: Deploy to IIS Production
          uses: echo "Deploy to Production Server"
          #T ODO